title: Beautiful Bullet Hell Toolkit
description: Beautiful Bullet Hell Toolkit
theme: just-the-docs

url: https://endlessnerd.github.io/BBHToolkit

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
